# 5. Matrix

This section will teach you how to create, manipulate, and work with Matrices effectively.

A **matrix** is a two-dimensional data structure that can hold elements of the same type, organized in rows and columns. Matrices are useful for mathematical computations, particularly linear algebra operations, and are a fundamental data structure in R for handling multi-dimensional data.

We'll learn about the following topics:

   - [5.1. Creating Matrices](#Creating_Matrices)
   - [5.2. Built-in Matrix Functions](#Builtin_Matrix_Functions)
   - [5.3. Matrix Indexing and Slicing](#Matrix_Indexing_and_Slicing)
   - [5.4. Matix Properties](#Matrix_Properties)

<a name='Creating_Matrices'></a>

## 5.1. Creating Matrices:

- **General Matrix Creation**: You can create a matrix in R using the `matrix()` function. The basic syntax is:

`matrix(data, nrow = number_of_rows, ncol = number_of_columns, byrow = FALSE, , dimnames = list(row_names, column_names))`

- data: The elements to fill the matrix.
- nrow: The number of rows.
- ncol: The number of columns.
- byrow: If TRUE, fills the matrix by rows; if FALSE (default), fills it by columns.
- dimnames: names of rows and columns

In [1]:
#Create a matrix with 3 rows and 3 columns
a <- matrix(1:9, nrow = 3, ncol = 3)

print(a)

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9


In [2]:
b <- matrix(1:9, nrow = 3, ncol = 3, byrow = TRUE,
                    dimnames = list(c("Row1", "Row2", "Row3"), c("Col1", "Col2", "Col3")))

print(b)

     Col1 Col2 Col3
Row1    1    2    3
Row2    4    5    6
Row3    7    8    9


To create a matrix where all rows and columns are filled by a single constant, write that constant instead of data.

In [3]:
#Create a special matrix with 3 rows and 3 columns
c <- matrix(1, nrow = 3, ncol = 3)

print(c)

     [,1] [,2] [,3]
[1,]    1    1    1
[2,]    1    1    1
[3,]    1    1    1


- **Diagonal matrix**: you can create a diagonal matrix using the `diag()` function. A diagonal matrix is a square matrix where all the elements outside the main diagonal are zero, and the diagonal elements can be any values.

`diag(numeric vector, nrow = number_of_rows, ncol = number_of_columns)`

In [4]:
d <- diag(c(1,7,6), nrow = 3, ncol = 3)

print(d)

     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    7    0
[3,]    0    0    6


- **Identity matrix**:  An identity matrix is a special type of square/diagonal matrix in which all the elements of the principal diagonal (from the top left to the bottom right) are ones, and all other elements are zeros.

`diag(n)`

- n: n*n matrix

In [5]:
e <- diag(3)

print(e)

     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    1    0
[3,]    0    0    1


<a name='Builtin_Matrix_Functions'></a>

## 5.2. Built-in Matrix Functions:

<table>
  <thead>
    <tr>
      <th>Function</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>dim()</td>
      <td>Gets or sets the dimensions of an object.</td>
    </tr>
    <tr>
      <td>nrow() and ncol()</td>
      <td>Get the number of rows and columns of a matrix, respectively.</td>
    </tr>
    <tr>
      <td>t()</td>
      <td>Transposes a matrix, swapping rows and columns.</td>
    </tr>
    <tr>
      <td>solve()</td>
      <td>Solves a system of linear equations or calculates the inverse of a matrix.</td>
    </tr>
    <tr>
      <td>cbind() and rbind()</td>
      <td>Combine matrices by columns or rows, respectively.</td>
    </tr>
    <tr>
      <td>diag()</td>
      <td>Create a diagonal matrix or extracts the diagonal of a matrix.</td>
    </tr>
    <tr>
      <td>apply()</td>
      <td>Applies a function over the margins of an array or matrix.</td>
    </tr>
    <tr>
      <td>length()</td>
      <td>Number of elements in the matrix.</td>
    </tr>
    <tr>
      <td>min() and max()</td>
      <td>Min and Max of all elements in the matrix.</td>
    </tr>
    <tr>
      <td>range()</td>
      <td>Get min and max of all elements at the same time.</td>
    </tr>
    <tr>
      <td>sum()</td>
      <td>Sum of all elements in the matrix.</td>
    </tr>
    <tr>
      <td>eigen()</td>
      <td>Calculate eigenvalues and eigenvectors of matrices.</td>
    </tr>
    <tr>
      <td>det()</td>
      <td>Used to find the determinant of a matrix.</td>
    </tr>
    <tr>
      <td>is.matrix()</td>
      <td>Check if the object is a matrix.</td>
    </tr>
    <tr>
      <td>as.matrix()</td>
      <td>Convert a numeric vector into a matrix.</td>
    </tr>
  </tbody>
</table>

**`dim()`**: Gets or sets the dimensions of an object.

In [6]:
dim(a)

[1] 3 3

**`nrow()`** and **`ncol()`**: Get the number of rows and columns of a matrix, respectively.

In [7]:
nrow(a)
ncol(a)

[1] 3

[1] 3

**`t()`**: Transposes a matrix, swapping rows and columns.

In [8]:
t(a)

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

**`solve()`**: Solves a system of linear equations or calculates the inverse of a matrix.

In [9]:
solve(a)

ERROR: Error in solve.default(a): Lapack routine dgesv: system is exactly singular: U[3,3] = 0


The error message you encountered when attempting to use the `solve()` function in R indicates that the matrix a is singular, which means that it does not have an inverse. A singular matrix has at least one of the following properties:

- It has linearly dependent rows or columns (i.e., one row can be expressed as a linear combination of others).
- Its determinant is zero, which means it cannot be inverted.

In [10]:
f <- matrix(c(4,6,1,8), nrow = 2, ncol = 2)

solve(f)

[,1]       [,2]       
[1,]  0.3076923 -0.03846154
[2,] -0.2307692  0.15384615

**`cbind()`** and **`rbind()`**: Combine matrices by columns or rows, respectively.

In [11]:
new_matrix1 <- cbind(a, a)
print(new_matrix1)

     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    1    4    7    1    4    7
[2,]    2    5    8    2    5    8
[3,]    3    6    9    3    6    9


In [12]:
new_matrix2 <- rbind(a, a)
print(new_matrix2)

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9
[4,]    1    4    7
[5,]    2    5    8
[6,]    3    6    9


**`diag()`**: Create a diagonal matrix or extracts the diagonal of a matrix.

In [13]:
diag(a)

[1] 1 5 9

**`apply()`**: Applies a function over the margins of an array or matrix.

`apply(X, MARGIN, FUN, ...)`

- X: The matrix to which the function will be applied.
- MARGIN: The dimension along which the function will be applied:

  1: Apply the function to each row.

  2: Apply the function to each column.
- FUN: The function to be applied to each row or column.

In [14]:
# Calculating the row sums of a matrix
row_sums <- apply(a, 1, sum)
print(row_sums)

[1] 12 15 18


In [15]:
#Calculating the column sums of a matrix
col_sums <- apply(a, 2, sum)
print(col_sums)

[1]  6 15 24


**`length()`**: Number of elements in the matrix.

In [16]:
length(a)

[1] 9

**`min()`** and **`max()`**: Min and Max of all elements in the matrix.

In [17]:
min(a)
max(a)

[1] 1

[1] 9

**`range()`**: Get min and max of all elements at the same time.

In [18]:
range(a)

[1] 1 9

**`sum()`**: Sum of all elements in the matrix.

In [19]:
sum(a)

[1] 45

**`eigen()`**: Calculate eigenvalues and eigenvectors of matrices.

In [20]:
eigen(a)

eigen() decomposition
$values
[1]  1.611684e+01 -1.116844e+00 -5.700691e-16

$vectors
           [,1]       [,2]       [,3]
[1,] -0.4645473 -0.8829060  0.4082483
[2,] -0.5707955 -0.2395204 -0.8164966
[3,] -0.6770438  0.4038651  0.4082483


**`det()`**: Used to find the determinant of matrix.

In [21]:
det(a)

[1] 0

**`is.matrix( )`**: Check if the Object is a Matrix.

In [22]:
is.matrix(a)

[1] TRUE

**`as.matrix()`**: Convert a numeric vector into a matrix.

In [23]:
#Create a numeric vector
vec <- c(1, 2, 3, 4, 5, 6)

#Convert the vector to a matrix with 2 rows and 3 columns
matrix_vec <- as.matrix(vec, nrow = 2, ncol = 3)

print(matrix_vec)

     [,1]
[1,]    1
[2,]    2
[3,]    3
[4,]    4
[5,]    5
[6,]    6


<a name='Matrix_Indexing_and_Slicing'></a>

## 5.3. Matrix Indexing and Slicing:

1. Numeric Indexing: You can access elements of a matrix by specifying their row and column indices.

- The syntax for indexing is `matrix[row, column]`.
- Indices start from 1, unlike Python, where they start from 0.
2. Logical Indexing: You can use logical vectors to index matrices, allowing you to select elements that meet certain conditions.

In [24]:
print(a)

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9


In [25]:
#Element in the second row and third column
a[2,3]

[1] 8

In [26]:
#Entire second row
a[2,]

[1] 2 5 8

In [27]:
#Entire second column
a[,2]

[1] 4 5 6

In [28]:
a[1,2:3]

[1] 4 7

In [29]:
a[1:3, 1:2]

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

You can also access multiple rows and columns by using a vector of indices.

In [30]:
a[c(1, 3), c(2, 3)]

[,1] [,2]
[1,] 4    7   
[2,] 6    9

Logical indexing allows you to select elements based on conditions.

In [31]:
a[a>5]

[1] 6 7 8 9

In R, using a negative index within a matrix indexing operation indicates that you want to exclude the specified row or column from the selection.

In [32]:
a[-1,]

[,1] [,2] [,3]
[1,] 2    5    8   
[2,] 3    6    9

<a name='Matrix_Properties'></a>

## 5.4. Matix Properties:

- **Reassignment**:

In [33]:
b

Col1 Col2 Col3
Row1 1    2    3   
Row2 4    5    6   
Row3 7    8    9

In [34]:
b[1,2] <- 22

b

Col1 Col2 Col3
Row1 1    22   3   
Row2 4     5   6   
Row3 7     8   9

- **Arithmetic Operations**: Arithmetic operations in R are typically applied element-wise. This means that when you perform an operation on two vectors of the same length, R will apply the operation to corresponding elements in each vector.

In [35]:
a
b

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

Col1 Col2 Col3
Row1 1    22   3   
Row2 4     5   6   
Row3 7     8   9

In [36]:
#Addition
a + b

Col1 Col2 Col3
Row1  2   26   10  
Row2  6   10   14  
Row3 10   14   18

In [37]:
#Subtraction
a - b

Col1 Col2 Col3
Row1  0   -18  4   
Row2 -2     0  2   
Row3 -4    -2  0

In [38]:
#Multiplication
a * b

Col1 Col2 Col3
Row1  1   88   21  
Row2  8   25   48  
Row3 21   48   81

In [39]:
#Division
a / b

Col1      Col2      Col3    
Row1 1.0000000 0.1818182 2.333333
Row2 0.5000000 1.0000000 1.333333
Row3 0.4285714 0.7500000 1.000000

In [40]:
#Floor Division
a %/% b

Col1 Col2 Col3
Row1 1    0    2   
Row2 0    1    1   
Row3 0    0    1

In [41]:
a ^ 2

[,1] [,2] [,3]
[1,] 1    16   49  
[2,] 4    25   64  
[3,] 9    36   81

In [42]:
2 * a

[,1] [,2] [,3]
[1,] 2     8   14  
[2,] 4    10   16  
[3,] 6    12   18

The Operator `%*%` is used for matrix multiplication satisfying the condition that the number of columns in the first matrix is equal to the number of rows in second. If matrix A[M, N] and matrix B[N, Z] are multiplied then the resultant matrix will be of dimension [M*Z].

In [43]:
m <- matrix(1:8, nrow=2)
n <- matrix(8:15, nrow=4)

m
n

[,1] [,2] [,3] [,4]
[1,] 1    3    5    7   
[2,] 2    4    6    8

[,1] [,2]
[1,]  8   12  
[2,]  9   13  
[3,] 10   14  
[4,] 11   15

In [44]:
print(m %*% n)

     [,1] [,2]
[1,]  162  226
[2,]  200  280
